repos:
  - id: codeberg.org/ScottyLabs/governance
    apply_requirements: [mergeable, undiverged]
    import_requirements: [mergeable, undiverged]
    allowed_overrides: [apply_requirements]
    allow_custom_workflows: false
    workflow: governance

  - id: codeberg.org/ScottyLabs/infrastructure
    plan_requirements: [mergeable]
    apply_requirements: [mergeable, undiverged]
    import_requirements: [mergeable, undiverged]
    allow_custom_workflows: false
    workflow: terranix
    pre_workflow_hooks:
      - run: install -m 644 "$(nix build --print-out-paths .#atlantis-yaml)" atlantis.yaml
        description: Generate atlantis.yaml from the flake

workflows:
  governance:
    plan:
      steps:
        - run: bash ../.forgejo/scripts/install-forgejo-provider.sh
        - env:
            name: CARGO_TARGET_DIR
            command: 'echo "$HOME/cargo-target"'
        - run: cargo build --release --manifest-path=../Cargo.toml -p governance
        - env:
            name: PATH
            command: 'echo "$CARGO_TARGET_DIR/release:$PATH"'
        - env:
            name: TF_CLI_CONFIG_FILE
            command: 'echo "$HOME/.terraform.d/dev_overrides.tfrc"'
        - init
        - plan
    apply:
      steps:
        - run: bash ../.forgejo/scripts/install-forgejo-provider.sh
        - env:
            name: CARGO_TARGET_DIR
            command: 'echo "$HOME/cargo-target"'
        - run: cargo build --release --manifest-path=../Cargo.toml -p governance
        - env:
            name: PATH
            command: 'echo "$CARGO_TARGET_DIR/release:$PATH"'
        - env:
            name: TF_CLI_CONFIG_FILE
            command: 'echo "$HOME/.terraform.d/dev_overrides.tfrc"'
        - apply
    import:
      steps:
        - run: bash ../.forgejo/scripts/install-forgejo-provider.sh
        - env:
            name: CARGO_TARGET_DIR
            command: 'echo "$HOME/cargo-target"'
        - run: cargo build --release --manifest-path=../Cargo.toml -p governance
        - env:
            name: PATH
            command: 'echo "$CARGO_TARGET_DIR/release:$PATH"'
        - env:
            name: TF_CLI_CONFIG_FILE
            command: 'echo "$HOME/.terraform.d/dev_overrides.tfrc"'
        - import

  terranix:
    plan:
      steps:
        - env:
            name: TF_WORKSPACE
            value: default
        - run: nix build ".#$PROJECT_NAME.config" --out-link config.tf.json
        - run: tofu init -input=false
        - run: tofu plan -input=false -out "$PLANFILE"
    apply:
      steps:
        - env:
            name: TF_WORKSPACE
            value: default
        - run: tofu apply -input=false "$PLANFILE"

metrics:
  prometheus:
    endpoint: /metrics
