name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-editorconfig:
    name: Check EditorConfig Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install EditorConfig Checker
        uses: taiki-e/install-action@v2
        with:
          tool: editorconfig-checker
          fallback: none

      - name: Check EditorConfig Compliance
        run: editorconfig-checker --exclude LICENSE

  check-opentofu:
    name: Check OpenTofu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed Terraform directories
        id: changed-terraform
        uses: tj-actions/changed-files@v46
        with:
          files: '**/*.tf'
          dir_names: true
          dir_names_max_depth: 10
          dir_names_exclude_current_dir: true
          json: true

      - name: Read OpenTofu version
        id: read_version
        run: echo "version=$(cat .opentofu-version)" >> $GITHUB_OUTPUT

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ steps.read_version.outputs.version }}

      - name: Run validation script
        if: steps.changed-terraform.outputs.any_changed == 'true'
        run: |
          echo '${{ steps.changed-terraform.outputs.all_changed_files }}' | \
          jq -r '.[]' | .github/scripts/validate.sh

      - name: Skip validation message
        if: steps.changed-terraform.outputs.any_changed == 'false'
        run: echo "No Terraform files changed, skipping validation"

      - name: Check formatting
        run: tofu fmt -recursive -check
