name: Deploy Infrastructure

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false # Don't cancel infrastructure deployments

# Required for OIDC token generation
permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    # Only run if the CI workflow was successful
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      services: ${{ steps.changes.outputs.services }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed services
        id: changed-services
        uses: tj-actions/changed-files@v46
        with:
          files: services/**
          dir_names: true # Emit unique changed directories instead of filenames
          dir_names_max_depth: 2
          dir_names_exclude_current_dir: true
          json: true

        # This returns services/service_name, trim to service_name
      - name: Set outputs
        id: changes
        run: |
          if [ "${{ steps.changed-services.outputs.any_changed }}" = "true" ]; then
            SERVICES=$(echo '${{ steps.changed-services.outputs.all_changed_files }}' | jq -c 'map(split("/")[1])')
            echo "services=$SERVICES" >> $GITHUB_OUTPUT
          else
            echo "services=[]" >> $GITHUB_OUTPUT
          fi

  plan:
    name: Plan (${{ matrix.service }}, ${{ matrix.environment }})
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.services != '[]'
    # Use GitHub environments for secrets and approval gates
    environment: ${{ matrix.environment }}
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
        environment: [dev, staging, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read OpenTofu version
        id: read_version
        run: echo "version=$(cat .opentofu-version)" >> $GITHUB_OUTPUT

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ steps.read_version.outputs.version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-actions-${{ matrix.service }}-${{ matrix.environment }}
          aws-region: us-east-2

      - name: Initialize OpenTofu
        working-directory: services/${{ matrix.service }}
        run: tofu init -backend-config="../../config/${{ matrix.environment }}.tfbackend"

      - name: Plan OpenTofu
        working-directory: services/${{ matrix.service }}
        # Specify -out so apply is guaranteed to take the exact same actions
        run: tofu plan -var-file="../../environments/${{ matrix.environment }}.tfvars" -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.service }}-${{ matrix.environment }}
          path: services/${{ matrix.service }}/tfplan

  apply:
    name: Apply (${{ matrix.service }}, ${{ matrix.environment }})
    runs-on: ubuntu-latest
    needs: [detect-changes, plan]
    if: needs.detect-changes.outputs.services != '[]' && github.event.workflow_run.head_branch == 'main'
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
        environment: [dev, staging, prod]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read OpenTofu version
        id: read_version
        run: echo "version=$(cat .opentofu-version)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-actions-${{ matrix.service }}-${{ matrix.environment }}
          aws-region: us-east-2

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ steps.read_version.outputs.version }}

      - name: Initialize OpenTofu
        working-directory: services/${{ matrix.service }}
        run: tofu init -backend-config="../../config/${{ matrix.environment }}.tfbackend"

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ matrix.service }}-${{ matrix.environment }}
          path: services/${{ matrix.service }}/

      - name: Apply OpenTofu
        working-directory: services/${{ matrix.service }}
        run: tofu apply tfplan
